# Generated by Django 4.0.2 on 2025-05-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(auto_created=True, auto_now_add=True, verbose_name='Data do Envio do Currículo')),
                ('firm', models.CharField(max_length=80, unique=True, verbose_name='Empresa')),
                ('name', models.CharField(max_length=255, verbose_name='Vaga')),
                ('salary', models.FloatField(max_length=80, verbose_name='Salário')),
                ('is_home', models.BooleanField(verbose_name='É home office?')),
                ('date_response', models.DateField(verbose_name='Data resposta')),
                ('offer', models.TextField(blank=True, max_length=400, null=True, verbose_name='Oferta/Resposta da empresa')),
            ],
        ),
    ]
